### ISSUE TITLE
memory requirements?

### ISSUE THREAD

**Issue by changliuxiaomi** [MichiganCOG/M-PACT#2]
Hi,

Just wonder what is the memory requirements for using M-PACT? I have Tesla p4 and 7G memory. When I run the train.py with ResNet50+LSTM I can see the memory goes up quickly,  almost reach 7GB before loading the weights. 

Can I ask the memory usage of M-PACT? Thanks,
Chang

**Comment by ehofesmann** [comment]
ResNet50+LSTM does require about 8.2GB of GPU memory if you want to train the entire model. 

One option is to freeze the ResNet50 portion and train only the LSTM. This can be done by setting the `--freeze 1` option to `--freeze 0` in your `python train.py` call.

Another option is to reduce the `seq_length` and `input_dims` number of frames to 30.  However, this may cause a drop in performance.

**Comment by changliuxiaomi** [comment]
Hi Thanks for the reply! I used to have a machine with 22GB which has not this problem of runing ResNet50+LSTM. That would be a good reason for upgrading the hardware.:)

By the way, is it possible to break down that how much memory are consumed on individual parts of M-PACT. For example, ResNet, LSTM and the tensorflow queue... Does the 8.2GB include the size of training item or it is just the memory consumption for training the network. 

Thanks.

**Comment by ehofesmann** [comment]
The [ArXiv paper introducing M-PACT](https://arxiv.org/abs/1804.05879) was updated to contain the memory requirements for different models in Table 2.
