### ISSUE TITLE
can not download the *.npy file as listed in "download_weights.sh"

### ISSUE THREAD

**Issue by leauyn** [MichiganCOG/M-PACT#6]
As mentioned above, I am not sure whether it is the network problem or these files have been removed from their sources, I have tried many times. These weights just can not be downloaded. Can anyone share them with me?

**Comment by ehofesmann** [comment]
I have uploaded the weights to two alternative file hosting sites: http://academictorrents.com/details/dcea7fa53925b31215bd8437d2f0805253d6b00f and https://app.nihaocloud.com/d/fb0c387c9a644f86b257/
